from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from openai import OpenAI
import os

# ✅ Use your OpenRouter API key directly (you can change later)
OPENROUTER_API_KEY = "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"

# Initialize OpenRouter client
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)

# ✅ Initialize FastAPI app
app = FastAPI()

# ✅ Allow frontend requests (replace with your actual site URL)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # you can later change this to ["https://house-of-prompts.web.app"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ Request model
class Article(BaseModel):
    article: str

# ✅ API route
@app.post("/analyze")
async def analyze(article: Article):
    try:
        prompt = f"""
        Analyze the credibility of this news article and provide:
        1. Credibility score out of 100%
        2. Short summary
        3. Counterarguments against its claims

        Article: {article.article}
        """

        response = client.chat.completions.create(
            model="deepseek/deepseek-r1:free",  # You can change to another free model if needed
            messages=[
                {"role": "system", "content": "You are a factual news credibility analyzer."},
                {"role": "user", "content": prompt},
            ],
        )

        message = response.choices[0].message.content

        return {
            "credibility_score": "AI-generated",
            "summary": message,
            "counterarguments": "Generated by AI"
        }

    except Exception as e:
        return {"error": str(e)}

@app.get("/")
def home():
    return {"message": "✅ News Analyzer API is running with OpenRouter!"}
